### ISSUE TITLE
Downloading error in the dashboard

### ISSUE THREAD

**Issue by DhruvWebDev** [piyush-eon/url-shortener#8]
the error is that when we click the download button in the dashboard, it does not download that in our software.
It just open the qr link in the new tab

**Comment by Ganesh121801** [comment]
> @DhruvWebDev  the error is that when we click the download button in the dashboard, it does not download that in our software. It just open the qr link in the new tab

yeah this error is causing in Link-card component where the browser is not recognising the generated url as downloadable but its redirecting to new tab due to its href ,you need to set the anchor.download attribute to the correct filename and make sure the image is fetched as a downloadable file for download 

the corrected function for this is  :




const downloadImage = () => {
    const imageUrl = url?.qr;
    const fileName = url?.title || "QR_Code"; 
  
    // Create a link element
    const anchor = document.createElement("a");
    anchor.href = imageUrl;
    anchor.download = fileName; 
    
    fetch(imageUrl)
      .then(response => response.blob())
      .then(blob => {
        const urlObject = URL.createObjectURL(blob);
        anchor.href = urlObject;
  
        // Trigger the download
        anchor.click();
  
    
        URL.revokeObjectURL(urlObject);
      })
      .catch(err => console.error("Download failed", err));
  };

**Comment by DhruvWebDev** [comment]
Thanks ):
